
import { createSlice } from '@reduxjs/toolkit';

const booksSlice = createSlice({
    name: 'books',
    initialState: {
        books: [
            { id: '1', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', description: `The Great Gatsby by F. Scott Fitzgerald is a classic novel set in the Roaring Twenties, following the mysterious and wealthy Jay Gatsby. Gatsby is obsessed with rekindling his past romance with Daisy Buchanan, a woman he met years before who is now married. The novel, narrated by Gatsby's neighbor Nick Carraway, explores themes of love, wealth, social class, and the American Dream. Through Gatsby's extravagant parties and tragic pursuit of his idealized love, Fitzgerald paints a vivid picture of the era's glamour, excess, and underlying emptiness.`, rating: 4.5, category: "Fiction", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIk0_tTyCjQk1MW3EC2p8adq0CEiDFUvZ-rg&s' },
            { id: '2', title: '1984', author: 'George Orwell', description: `1984 by George Orwell is a dystopian novel set in a totalitarian society controlled by the Party and its leader, Big Brother. The story follows Winston Smith, a low-ranking Party member who secretly despises the oppressive regime and longs for freedom and truth. Under constant surveillance, Winston risks everything to rebel against the Party's manipulation and rewriting of history. Orwell's novel explores themes of government control, surveillance, and the dangers of totalitarianism, offering a chilling warning about the loss of individuality and truth in a world governed by propaganda.`, rating: 4.7, category: "Non-Fiction", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNWbRCxT4Eo1oj6C-6zqSZy2LYUiPORR_uZQ&s' },
            { id: '3', title: 'To Kill a Mockingbird', author: 'Harper Lee', description: `To Kill a Mockingbird by Harper Lee is a powerful novel set in the racially segregated American South during the 1930s. The story is narrated by young Scout Finch, who watches as her father, lawyer Atticus Finch, defends a Black man, Tom Robinson, falsely accused of raping a white woman. Through Scout’s eyes, the novel explores themes of racial injustice, moral growth, and empathy. As Scout and her brother, Jem, confront prejudice and learn valuable lessons about humanity, the novel sheds light on the importance of integrity and standing up for what is right, even in the face of widespread bigotry.`, rating: 4.8, category: "Fiction", imageUrl: 'https://media.glamour.com/photos/56e1f3c41632e6ca44c16e9e/master/w_1600%2Cc_limit/entertainment-2016-02-13-main.jpg' },
            { id: '4', title: 'The Catcher in the Rye', author: 'J.D. Salinger', description: `The Catcher in the Rye by J.D. Salinger follows the story of Holden Caulfield, a disenchanted teenager who has just been expelled from his prep school. Narrated in a colloquial style, the novel captures Holden's inner turmoil as he navigates the complexities of adolescence, alienation, and the loss of innocence in post-war America. Over the course of a few days in New York City, he encounters various people and experiences that deepen his sense of isolation and longing for connection. The title refers to Holden's fantasy of being "the catcher in the rye," protecting children from the harsh realities of adulthood, which highlights his desire to preserve innocence in a world he perceives as phony.`, rating: 4.2, category: "Sci-Fi", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdCccbSjGEZmXTRieG4ygyccR-MjdiIApLow&s' },
            { id: '5', title: 'Pride and Prejudice', author: 'Jane Austen', description: `Pride and Prejudice by Jane Austen is a beloved romantic novel set in early 19th-century England. It follows the spirited Elizabeth Bennet as she navigates issues of class, marriage, and morality in a society that values wealth and status. The story centers on her evolving relationship with the wealthy and seemingly proud Mr. Darcy, whose initial arrogance masks a deeper integrity and vulnerability. Through witty dialogue and keen social commentary, Austen explores themes of pride, prejudice, and the importance of self-awareness, ultimately revealing that true understanding and love transcend social boundaries and personal biases. The novel remains a timeless exploration of love and human relationships.`, rating: 4.6, category: "Romance", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5-nNu0rajX4G_x3Ogq53GSoAeIRiOLaQ0pg&s' },
            { id: '6', title: 'Brave New World', author: 'Aldous Huxley', description: `Brave New World by Aldous Huxley is a dystopian novel set in a technologically advanced future where society prioritizes stability, uniformity, and consumerism over individuality and emotional depth. In this world, humans are genetically engineered and conditioned for their roles in a rigid caste system, and the use of a drug called "soma" suppresses any feelings of unhappiness or discontent. The story follows Bernard Marx, an outsider who feels alienated from the conformist society, and John, a "savage" raised outside the World State. As Bernard and John confront the values of their respective worlds, Huxley examines themes of freedom, the dangers of an all-powerful state, and the cost of sacrificing individuality for societal happiness.`, rating: 4.4, category: "Sci-Fi", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvnduQM-M1uFRKDL45skzKxeOHfE9Fleabvg&s' },
        ],
    },
    reducers: {
        addBook: (state, action) => {
            // Use the ID based on the current state length + 1 for new books
            const newId = (state.books.length + 1).toString();
            state.books.push({ ...action.payload, id: newId }); // Assign a new ID for the added book
        },
    },
});

export const { addBook } = booksSlice.actions;
export default booksSlice.reducer;
